# general configuration
url: http://trommel.github.io
baseurl: ''

# compass configuration
compass:
  # an avatar or logo (optional)
  logo: "/images/avatar.jpg"
  # author will appear under the avatar (optional)
  author: "Josh Trommel"
  # tagline will appear under the title (optional)
  tagline: "I'm still thinking of something extremely clever to write here."
  # if include_content is true, the contents of the content.html include will be
  # added right above the generated item list, if present
  include_content: true
  # if include_analytics is true, the content of the analytics.html include will
  # be added at the end of the <head> section. You can add your Google Analytics
  # Tracking Code to that file.
  include_analytics: false

# Dependencies
markdown: kramdown
highlighter: pygments

# Permalinks
permalink: pretty
relative_permalinks: true
