# Site settings
title: things that happen to me
email: joshception@icloud.com
description: hi i'm josh let's be friends
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://trommel.github.com" # the base hostname & protocol for your site
twitter_username: nulljosh
github_username:  trommel

# Build settings
markdown: kramdown
