# Site settings
title: Josh Trommel | Incompetant Developer 
description: "I like code, nice people, and comfy blankets."
url: "https://joshtrommel.com"
author:
  name: "Josh Trommel"
  email: "joshtrommel@gmail.com"
  url: "http://joshtrommel.com"

# Build settings
baseurl: / # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Custom variables
version: "1.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
