name: "Josh Trommel"
description: "guy"

author: "Josh Trommel"

url: "http://trommel.github.io"
baseurl: "http://trommel.github.io"

markdown: rdiscount
permalink: :year/:month/:title.html
pygments: true

# Google Analytics
ga_domain: trommel.github.io
ga_tracking_id: UA-47727049-1
