name: "josh trommel"
description: "i like cute girls & code"

author: "Josh Trommel"

url: "http://trommel.github.io"
baseurl: "http://trommel.github.io"

markdown: rdiscount
permalink: :month/:year/:title.html
pygments: true

# Google Analytics
ga_domain: m3xm.github.io
ga_tracking_id: UA-47727049-1
